[package]
name = "minihttp"
version = "0.1.0"
authors = ["Alexey Popravka <alexey.popravka@horsedevel.com>"]

[dependencies]

futures = "0.1.3"
httparse = "1.1.2"
tokio-core = "0.1.0"
tokio-service = { git = "https://github.com/tokio-rs/tokio-service", rev="da47a93" }
tk-bufstream = "0.1.0"
netbuf = "0.3.7"
quick-error = "1.1.0"
matches = "0.1.3"
log = "0.3.6"
curl = "0.3.8"
tokio-curl = "0.1.3"

[dev-dependencies]
env_logger = "0.3.5"
argparse = "0.2.1"
tk-sendfile = "0.3.0"
futures-cpupool = "0.1.2"
time = "0.1.35"
